branches:
  only:
  - 'v2.2-dev'
  - 'mr_private/MR-v2.2-dev-playground'
  - 'scala_versionbump'
  - 'deskshare_fixes'

language: scala
scala:
- 2.12.6

jdk:
- oraclejdk8
#- openjdk8
- oraclejdk10
- openjdk10
- openjdk11

node_js: 9

addons:
  apt:
    sources:
    - sourceline: 'ppa:cwchien/gradle'
    packages:
    - gradle-4.7

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.ivy2"
  - "$HOME/.meteor"
  - "$HOME/.cordova"
  - "$HOME/.npm"
  - "$HOME/.node-gyp"
  - "$HOME/.gradle"
  - "$HOME/.grails"

env:
  global:
  - BUILD_DIRECTORY=$TRAVIS_BUILD_DIR/build_results
  - RED5APPSDIR=$BUILD_DIRECTORY/red5/webapps
  - TOMCATAPPSDIR=$BUILD_DIRECTORY/tomcat/webapps
  - HTML5METEOR=$BUILD_DIRECTORY/html5meteor
  - METEOR_DEBUG_BUILD=1
  - BBB_LOGPATH=$BUILD_DIRECTORY/logs

before_install:
- echo '***************************' && echo 'bbb travis build script v19' && echo '***************************'
- curl -s http://get.sdkman.io | bash
- echo sdkman_auto_answer=true > ~/.sdkman/etc/config && source "/home/travis/.sdkman/bin/sdkman-init.sh" && sdk install grails 2.5.2
- mkdir -pv $RED5APPSDIR
- mkdir -pv $TOMCATAPPSDIR
- mkdir -pv $HTML5METEOR
- mkdir -pv $BBB_LOGPATH
- echo 'done creating directories'
- ls -l $HOME && df -h
  #
  # removing some stuff to save space (see below, we ran into disk space issues earlier
  #
- sudo sudo apt-get -y purge postgresql-9.2
- sudo sudo apt-get -y purge postgresql-9.3
- sudo sudo apt-get -y purge postgresql-9.4
- sudo sudo apt-get -y purge postgresql-9.5
- sudo sudo apt-get -y purge postgresql-9.6
- sudo sudo apt-get -y purge postgresql-common
- sudo apt -y purge mysql-server-5.6
- sudo apt -y autoremove
- |
  keytool -import -trustcacerts -alias sonatype -keystore $JAVA_HOME/JRE/lib/security/cacerts -storepass changeit -file - << EOF
  -----BEGIN CERTIFICATE-----
  MIIEDzCCAvegAwIBAgIBADANBgkqhkiG9w0BAQUFADBoMQswCQYDVQQGEwJVUzEl
  MCMGA1UEChMcU3RhcmZpZWxkIFRlY2hub2xvZ2llcywgSW5jLjEyMDAGA1UECxMp
  U3RhcmZpZWxkIENsYXNzIDIgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkwHhcNMDQw
  NjI5MTczOTE2WhcNMzQwNjI5MTczOTE2WjBoMQswCQYDVQQGEwJVUzElMCMGA1UE
  ChMcU3RhcmZpZWxkIFRlY2hub2xvZ2llcywgSW5jLjEyMDAGA1UECxMpU3RhcmZp
  ZWxkIENsYXNzIDIgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkwggEgMA0GCSqGSIb3
  DQEBAQUAA4IBDQAwggEIAoIBAQC3Msj+6XGmBIWtDBFk385N78gDGIc/oav7PKaf
  8MOh2tTYbitTkPskpD6E8J7oX+zlJ0T1KKY/e97gKvDIr1MvnsoFAZMej2YcOadN
  +lq2cwQlZut3f+dZxkqZJRRU6ybH838Z1TBwj6+wRir/resp7defqgSHo9T5iaU0
  X9tDkYI22WY8sbi5gv2cOj4QyDvvBmVmepsZGD3/cVE8MC5fvj13c7JdBmzDI1aa
  K4UmkhynArPkPw2vCHmCuDY96pzTNbO8acr1zJ3o/WSNF4Azbl5KXZnJHoe0nRrA
  1W4TNSNe35tfPe/W93bC6j67eA0cQmdrBNj41tpvi/JEoAGrAgEDo4HFMIHCMB0G
  A1UdDgQWBBS/X7fRzt0fhvRbVazc1xDCDqmI5zCBkgYDVR0jBIGKMIGHgBS/X7fR
  zt0fhvRbVazc1xDCDqmI56FspGowaDELMAkGA1UEBhMCVVMxJTAjBgNVBAoTHFN0
  YXJmaWVsZCBUZWNobm9sb2dpZXMsIEluYy4xMjAwBgNVBAsTKVN0YXJmaWVsZCBD
  bGFzcyAyIENlcnRpZmljYXRpb24gQXV0aG9yaXR5ggEAMAwGA1UdEwQFMAMBAf8w
  DQYJKoZIhvcNAQEFBQADggEBAAWdP4id0ckaVaGsafPzWdqbAYcaT1epoXkJKtv3
  L7IezMdeatiDh6GX70k1PncGQVhiv45YuApnP+yz3SFmH8lU+nLMPUxA2IGvd56D
  eruix/U0F47ZEUD0/CwqTRV/p2JdLiXTAAsgGh1o+Re49L2L7ShZ3U0WixeDyLJl
  xy16paq8U4Zt3VekyvggQQto8PT7dL5WXXp59fkdheMtlb71cZBDzI0fmgAKhynp
  VSJYACPq4xJDKVtHCN2MQWplBqjlIapBtJUhlbl90TSrE9atvNziPTnNvT51cKEY
  WQPJIrSPnNVeKtelttQKbfi3QBFGmh95DmK/D5fs4C8fF5Q=
  -----END CERTIFICATE-----
  EOF
  
script:
  # libraries
- cd $TRAVIS_BUILD_DIR/bbb-common-message && sbt clean update  publish publishLocal
- cd $TRAVIS_BUILD_DIR/bbb-common-web && sbt clean update  publish publishLocal
- cd $TRAVIS_BUILD_DIR/bbb-apps-common && sbt clean update  publish publishLocal
- cd $TRAVIS_BUILD_DIR/bbb-fsesl-client && sbt clean update  publish publishLocal
# packages
- cd $TRAVIS_BUILD_DIR/akka-bbb-apps && sbt clean update package  publish publishLocal
- cd $TRAVIS_BUILD_DIR/akka-bbb-fsesl && sbt clean update package publish publishLocal
- cd $TRAVIS_BUILD_DIR/akka-bbb-transcode && sbt clean update package publish publishLocal
#//todo: package content od target directory
  #
  # cleaning up sources of already built libraries as we ran into 'No Space Left on Device' issues at some point about here
  #
- rm -rf $TRAVIS_BUILD_DIR/bbb-common-message
- rm -rf $TRAVIS_BUILD_DIR/bbb-common-web
- rm -rf $TRAVIS_BUILD_DIR/bbb-apps-common
- rm -rf $TRAVIS_BUILD_DIR/bbb-fsesl-client
- rm -rf $TRAVIS_BUILD_DIR/akka-bbb-apps
- rm -rf $TRAVIS_BUILD_DIR/akka-bbb-fsesl
- rm -rf TRAVIS_BUILD_DIR/akka-bbb-transcode
  #
  # building the core backend applications
  #
- echo building bbb-voice
- cd $TRAVIS_BUILD_DIR/bbb-voice
- /usr/lib/gradle/4.7/bin/gradle clean
- /usr/lib/gradle/4.7/bin/gradle resolveDeps
- /usr/lib/gradle/4.7/bin/gradle war
- /usr/lib/gradle/4.7/bin/gradle deploy
  #
- echo building bbb-video
- cd $TRAVIS_BUILD_DIR/bbb-video
- /usr/lib/gradle/4.7/bin/gradle clean
- /usr/lib/gradle/4.7/bin/gradle resolveDeps
- /usr/lib/gradle/4.7/bin/gradle war
- /usr/lib/gradle/4.7/bin/gradle deploy
  #
- echo building bigbluebutton-apps
- cd $TRAVIS_BUILD_DIR/bigbluebutton-apps
- /usr/lib/gradle/4.7/bin/gradle clean
- /usr/lib/gradle/4.7/bin/gradle resolveDeps
- /usr/lib/gradle/4.7/bin/gradle war
- /usr/lib/gradle/4.7/bin/gradle deploy
  #
- rm -rf TRAVIS_BUILD_DIR/bbb-voice
- rm -rf TRAVIS_BUILD_DIR/bbb-video
- rm -rf TRAVIS_BUILD_DIR/bigbluebutton-apps
  #
  # building tomcat core webapp (server+api)
  #
#- echo 'building web app'
#- cd $TRAVIS_BUILD_DIR/bigbluebutton-web
#  #//todo: sheck version upgrade latest grails2 and grails3 - grails set-grails-version # when not compiling with grails 2.5.2 but the most recent grails2
#- /usr/lib/gradle/4.7/bin/gradle properties
#- /usr/lib/gradle/4.7/bin/gradle clean
#- /usr/lib/gradle/4.7/bin/gradle resolveDeps
#- grails clean
#- grails compile
#- grails war
#- /usr/lib/gradle/4.7/bin/gradle deploy
##//todo: move grails compile into gradle (grails plugin)
##
#- echo 'building API demo'
#- cd $TRAVIS_BUILD_DIR/bbb-api-demo
#- /usr/lib/gradle/4.7/bin/gradle clean
#- /usr/lib/gradle/4.7/bin/gradle resolveDeps
#- /usr/lib/gradle/4.7/bin/gradle war
#- /usr/lib/gradle/4.7/bin/gradle deploy
##
#- echo 'building bbb-lti service'
#- cd $TRAVIS_BUILD_DIR/bbb-lti
#  #- grails set-grails-version # when not compiling with grails 2.5.2 but the most recent grails2
#- grails clean
#- grails compile
#- grails war
##
#- echo 'building deskshare app'
#- cd $TRAVIS_BUILD_DIR/deskshare
#- /usr/lib/gradle/4.7/bin/gradle clean
#- /usr/lib/gradle/4.7/bin/gradle resolveDeps
#- /usr/lib/gradle/4.7/bin/gradle war
#- /usr/lib/gradle/4.7/bin/gradle deploy
##
#
#- find $BUILD_DIRECTORY -maxdepth 3 -type d -exec ls -l {} \; -print
#  #
#  # building the html5 meteor backend and (web-(client
#  #
#- cd $HOME && curl https://install.meteor.com | sh
#- cd $TRAVIS_BUILD_DIR/bigbluebutton-html5 && meteor npm install && meteor npm install @babel/runtime
#  #   - meteor remove standard-minifier-js
#  # make active in case minifier causes travis to time out again (this thing takes loooong
#- cd $TRAVIS_BUILD_DIR/bigbluebutton-html5
#- meteor remove standard-minifier-js
#- meteor build $HTML5METEOR --directory --server-only --architecture=os.linux.x86_64
#  #- cd $HTML5METEOR/bundle/programs/server && npm install --production
#  #
#
#before_deploy:
#- cd $BUILD_DIRECTORY
#- tar -cvf red5webapps.tar $RED5APPSDIR
#- tar -cvf tomcatwebapps.tar $TOMCATAPPSDIR
#- tar -cvf bbb_javalibs.tar $HOME/.ivy2
#- tar -cvf bbb-html5.tar $HTML5METEOR
#- ls -rtl $BUILD_DIRECTORY
#
#deploy:
#  provider: releases
#  api_key:
#    secure: "cTb2AA8SqAAYmnGwN4RkTVxjHtMj5i+mCh2PsgTmXkdO8r9XNdmL1/fpyCcS1v0PLOhPEJbk8lzYWMiPCAxMJ1HrmEIctORwyKMDyv6tattsRaqUpVc1wD728QZ3ZEKA61h+bQy20rXkgotpzHnsDMRp6eokzLfUrSN530+sa2di69r3ACRSkNbuFbraoUpXQVAPvv1tiiS7ZqtNjva2Zx7UZpx8evYs06eXij6/oSNZvwRdcbsNWYuo/MUI/XQ+dInzf/0KIqKtfVF9RoU3fre4vuqNlW0qFJcxAJ3RoTVY4f/oi3HD+61ecbPEesLkTFY1C3EpQYrzIJg4owz/FQR/60/hKjDaCOzn5LmVBSDDY9KZrz/+DiJPjftUgT/NNdX+g+dD+xGMBJ/lbu8UxU0qIESq1Djk/Z50pRZEwIx0j6Y8GYI0pImcv8vF0n/NdK9qSu+ilzruHiJgNBpjYu/wn4PsfYH2fMDGPODZJhjft56pN+zAE73v5yZtAkSikwZ+2Jh78TZaKHRactdNh/hlF49aZLSBP1T9YsJLyDCjl70nINsGcDaf1g8+6v1BlMob7Lqd22FwrDQ6pMAWGR2LbriZ0hmakhY5GUjTtUr1RoSMUtYE2/XCSBo+dcYpdGWRCW0kygr9dasyF6598yQomO9kZtQ1xvN+kXOcrdU="
#  file:
#    - "$BUILD_DIRECTORY/red5webapps.tar"
#    - "$BUILD_DIRECTORY/tomcatwebapps.tar"
#    - "$BUILD_DIRECTORY/bbb_javalibs.tar"
#    - "$BUILD_DIRECTORY/bbb-html5.tar"
#  skip_cleanup: true
#  on:
#    branch: 'mr_private/MR-v2.2-dev-playground'
