branches:
  only:
  - 'v2.2-dev'
  - 'MR-v2.2-dev-playground'

language: scala
scala:
- 20.10.4
- 2.12.7

jdk:
- oraclejdk8
- openjdk8
- oraclejdk10

node_js: 9

addons:
  apt:
    sources:
    - sourceline: 'ppa:cwchien/gradle'
    packages:
    - gradle-4.7

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.ivy2"
  - "$HOME/.meteor"
  - "$HOME/.cordova"
  - "$HOME/.npm"
  - "$HOME/.node-gyp"
  - "$HOME/.gradle"
  - "$HOME/.grails"

env:
  global:
  - BUILD_DIRECTORY=$TRAVIS_BUILD_DIR/build_results
  - RED5APPSDIR=$BUILD_DIRECTORY/red5/webapps
  - TOMCATAPPSDIR=$BUILD_DIRECTORY/tomcat/webapps
  - HTML5METEOR=$BUILD_DIRECTORY/html5meteor
  - METEOR_DEBUG_BUILD=1
  - BBB_LOGPATH=$BUILD_DIRECTORY/logs

before_install:
- curl -s http://get.sdkman.io | bash
- echo sdkman_auto_answer=true > ~/.sdkman/etc/config
- source "/home/travis/.sdkman/bin/sdkman-init.sh"
- sdk install grails 2.5.2
- mkdir -pv $RED5APPSDIR
- mkdir -pv $TOMCATAPPSDIR
- mkdir -pv $HTML5METEOR
- mkdir -pv $BBB_LOGPATH
- echo done creating directories
- ls -l $HOME && df -h
  #
  # removing some stuff to save space (see below, we ran into disk space issues earlier
  #
- sudo sudo apt-get -y purge postgresql-9.2
- sudo sudo apt-get -y purge postgresql-9.3
- sudo sudo apt-get -y purge postgresql-9.4
- sudo sudo apt-get -y purge postgresql-9.5
- sudo sudo apt-get -y purge postgresql-9.6
- sudo sudo apt-get -y purge postgresql-common
- sudo apt -y purge mysql-server-5.6
- sudo apt -y autoremove

script:
- cd $TRAVIS_BUILD_DIR/bbb-common-message && sbt clean publish publishLocal
- cd $TRAVIS_BUILD_DIR/bbb-common-web && sbt clean publish publishLocal
- cd $TRAVIS_BUILD_DIR/bbb-apps-common && sbt clean publish publishLocal
- cd $TRAVIS_BUILD_DIR/bbb-fsesl-client && sbt clean publish publishLocal
- cd $TRAVIS_BUILD_DIR/akka-bbb-apps && sbt clean publish publishLocal
- cd $TRAVIS_BUILD_DIR/akka-bbb-fsesl && sbt clean publish publishLocal
- cd $TRAVIS_BUILD_DIR/akka-bbb-transcode && sbt clean publish publishLocal
  #
  # cleaning up as we ran into 'No Space Left on Device' issues at some point about here
  #
- rm -rf $TRAVIS_BUILD_DIR/bbb-common-message
- rm -rf $TRAVIS_BUILD_DIR/bbb-common-web
- rm -rf $TRAVIS_BUILD_DIR/bbb-apps-common
- rm -rf $TRAVIS_BUILD_DIR/bbb-fsesl-client
- rm -rf $TRAVIS_BUILD_DIR/akka-bbb-apps
- rm -rf $TRAVIS_BUILD_DIR/akka-bbb-fsesl
- rm -rf TRAVIS_BUILD_DIR/akka-bbb-transcode
  #
  # building the core backend applications
  #
- echo building bbb-voice
- cd $TRAVIS_BUILD_DIR/bbb-voice
- /usr/lib/gradle/4.7/bin/gradle clean
- /usr/lib/gradle/4.7/bin/gradle resolveDeps
- /usr/lib/gradle/4.7/bin/gradle war
- ls -rtl
- /usr/lib/gradle/4.7/bin/gradle deploy
 #
- echo building bbb-video
- cd $TRAVIS_BUILD_DIR/bbb-voice
- /usr/lib/gradle/4.7/bin/gradle clean
- /usr/lib/gradle/4.7/bin/gradle resolveDeps
- /usr/lib/gradle/4.7/bin/gradle war
- ls -rtl
- /usr/lib/gradle/4.7/bin/gradle deploy
  #
- echo building bigbluebutton-apps
- cd $TRAVIS_BUILD_DIR/bbb-voice
- /usr/lib/gradle/4.7/bin/gradle clean
- /usr/lib/gradle/4.7/bin/gradle resolveDeps
- /usr/lib/gradle/4.7/bin/gradle war
- ls -rtl
- /usr/lib/gradle/4.7/bin/gradle deploy
  #
- rm -rf TRAVIS_BUILD_DIR/bbb-voice
- rm -rf TRAVIS_BUILD_DIR/bbb-video
- rm -rf TRAVIS_BUILD_DIR/bigbluebutton-apps
  #
  # building tomcat core webapp (api)
  #
- echo building web app
- cd $TRAVIS_BUILD_DIR/bigbluebutton-web
- mkdir -pv build   # openjdk throwing an error otherwisse, //TOTO: fix in gradle build file
#- grails set-grails-version # when not compiling with grails 2.5.2 but the most recent grails2
- gradle properties
- /usr/lib/gradle/4.7/bin/gradle properties
- /usr/lib/gradle/4.7/bin/gradle clean
- /usr/lib/gradle/4.7/bin/gradle resolveDeps
- grails clean
- grails compile
- grails war
- ls -rtl
- /usr/lib/gradle/4.7/bin/gradle deploy
  #
  # building the html5 meteor backend and (web-(client
  #
- cd $HOME && sudo npm i -g npm
- cd $HOME && curl https://install.meteor.com | sh
- cd $TRAVIS_BUILD_DIR/bigbluebutton-html5 && meteor npm install && meteor npm install @babel/runtime
  #   - meteor remove standard-minifier-js
  # make active in case minifier causes travis to time out again (this thing takes loooong
- cd $TRAVIS_BUILD_DIR/bigbluebutton-html5
- travis_wait 50 meteor build $HTML5METEOR --directory --server-only --architecture=os.linux.x86_64
#- cd $HTML5METEOR/bundle/programs/server && npm install --production
 #
- ls -Rrtl $BUILD_DIRECTORY

before_deploy:
- cd $BUILD_DIRECTORY
- tar -cvf red5webapps.tar $RED5APPSDIR
- tar -cvf bbb_javalibs.tar $HOME/.ivy2
- tar -cvf bbb-html5.tar $HTML5METEOR
- ls -al && df -h

